# Default configuration for cerebras-code-monitor
session-token: ""
org-id: ""
model: "qwen-3-coder-480b"
refresh-rate: 10
refresh-per-second: 0.75
timezone: "auto"
time-format: "auto"
theme: "auto"
log-level: "INFO"
log-file: ""
debug: false
clear: false
icons: "emoji"  # Options: "emoji" or "nerdfont"
